{-# LANGUAGE MagicHash #-}

{-# LANGUAGE BangPatterns #-}

{-# LANGUAGE TypeSynonymInstances #-}

{-# LANGUAGE FlexibleInstances #-}

{-# LANGUAGE PatternGuards #-}

{-# LANGUAGE NoStrictData #-}

{-# LANGUAGE UnboxedTuples #-}

{-# LANGUAGE PartialTypeSignatures #-}



-- parser (data) produced by Happy (GLR) Version 2.2

module TurtleParserData where



import TurtleLexer
import qualified Control.Monad as Happy_Prelude
import qualified Data.Bool as Happy_Prelude
import qualified Data.Function as Happy_Prelude
import qualified Data.Int as Happy_Prelude
import qualified Data.List as Happy_Prelude
import qualified Data.Maybe as Happy_Prelude
import qualified Data.String as Happy_Prelude
import qualified Data.Tuple as Happy_Prelude
import qualified GHC.Err as Happy_Prelude
import qualified GHC.Num as Happy_Prelude
import qualified Text.Show as Happy_Prelude
import qualified Data.Array as Happy_Data_Array
import qualified Data.Bits as Bits
import qualified GHC.Exts as Happy_GHC_Exts
import Control.Applicative(Applicative(..))
import Control.Monad (ap)



{- GLR_Base.lhs
   $Id: GLR_Base.lhs,v 1.4 2004/12/04 15:01:37 paulcc Exp $
-}

-- Basic defs required for compiling the data portion of the parser

-- We're creating Int-indexed graphs

type ForestId  = (Int,Int,GSymbol)


-- Actions for the GLR machine

data GLRAction = Shift Int [Reduction]
               | Reduce [Reduction]
               | Accept
               | Error

---
-- A Reduction (s,n,f) removes the top n node-ids, creates a new branch from these
-- and labels the branch with the given symbol s. Additionally, the branch may
-- hold some semantic value.

type Reduction = (GSymbol,Int, [ForestId] -> Branch)


---
-- A Branch holds the semantic result plus node ids of children

data Branch
 = Branch {b_sem :: GSem, b_nodes :: [ForestId]}
   deriving Show

instance Eq Branch where
        b1 == b2 = b_nodes b1 == b_nodes b2



-------------------------------------------------------------------------------
-- Utilities for decoding

---
-- Tree decode unpacks the forest into a list of results
--  - this is ok for small examples, but inefficient for very large examples
--  - the data file contains further instances
--  - see documentation for further information
--  - "Decode_Result" is a synonym used to insert the monad type constr (or not)

class TreeDecode a where
        decode_b :: (ForestId -> [Branch]) -> Branch -> [Decode_Result a]

decode :: TreeDecode a => (ForestId -> [Branch]) -> ForestId -> [Decode_Result a]
decode f i@(_,_,HappyTok t)
  = decode_b f (Branch (SemTok t) [])
decode f i
  = [ d | b <- f i, d <- decode_b f b ]

---- generated by Happy, since it means expansion of synonym (not ok in H-98)
--instance TreeDecode UserDefTok where
--      decode_b f (Branch (SemTok t) []) = [happy_return t]

---
-- this is used to multiply the ambiguous possibilities from children

--cross_fn :: [a -> b] -> [a] -> [b]
--actual type will depend on monad in use.
--happy_ap defined by parser generator
cross_fn fs as = [ f `happy_ap` a | f <- fs, a <- as]

---
-- Label decoding unpacks from the Semantic wrapper type
--  - this allows arbitrary values (within the limits of the compiler settings)
--    to be recovered from nodes in the tree.
--  - again, more instances are written in the data file
--  - see documentation for further information

class LabelDecode a where
        unpack :: GSem -> a

---- generated by Happy, since it means expansion of synonym (not ok in H-98)
--instance LabelDecode UserDefTok where
--      unpack (SemTok t) = t




{-# LINE 114 "TurtleParserData.hs"#-}

parseError :: [Token] -> a
parseError = undefined

data Directive 
  = CBase String 
  | CPrefix String String
  deriving (Eq, Show)

data AbbrURI 
  = CURI String 
  | CAUIR String String
  deriving (Eq, Show)

data Object 
  = CObjects Object Object 
  | COURI AbbrURI 
  | COStr String 
  | COInt Int
  deriving (Eq, Show)

data PredicateT 
  = CPredicate AbbrURI Object 
  | CPredicateP Predicate Predicate
  deriving (Eq, Show)

data TurtleDoc
  = CDirective Directive 
  | CTripples AbbrURI Predicates
  deriving (Eq, Show)

{-# LINE 146 "TurtleParserData.hs"#-}

data GSymbol = HappyEOF | HappyTok {-!Int-} (Token) | G_TurtleDoc 
 | G_Directive 
 | G_AbbrURI 
 | G_Predicates 
 | G_Object 
   deriving (Show,Eq,Ord)

data GSem
 = NoSem
 | SemTok (Token) | Sem_0 (()) 
 | Sem_1 (()) 
 | Sem_2 (()) 
 | Sem_3 (()) 
 | Sem_4 (()) 
   deriving (Show)


semfn_0_0 ns@(happy_var_1:happy_rest) =  Branch (Sem_0 (CDirective happy_var_1)) ns
semfn_0_1 ns@((_,_,HappyTok ((TokenURI happy_var_1))):happy_rest) =  Branch (Sem_0 (CURI happy_var_1)) ns
semfn_0_2 ns@(happy_var_1:happy_rest) =  Branch (Sem_0 (COURI happy_var_1)) ns
semfn_0_3 ns@((_,_,HappyTok ((TokenString happy_var_1))):happy_rest) =  Branch (Sem_0 (COStr happy_var_1)) ns
semfn_0_4 ns@((_,_,HappyTok ((TokenInteger happy_var_1))):happy_rest) =  Branch (Sem_0 (COInt happy_var_1)) ns
semfn_1_0 ns@(happy_var_1:happy_var_2:happy_rest) =  Branch (Sem_1 (CTripples happy_var_1 happy_var_2)) ns
semfn_1_1 ns@(happy_var_1:happy_var_2:happy_rest) =  Branch (Sem_1 (CTurtleDocP happy_var_1 happy_var_2)) ns
semfn_1_2 ns@(happy_var_1:happy_var_2:happy_rest) =  Branch (Sem_1 (CPredicate happy_var_1 happy_var_2)) ns
semfn_2_0 ns@(happy_var_1:(_,_,HappyTok ((TokenURI happy_var_2))):happy_rest) =  Branch (Sem_2 (CBase happy_var_2)) ns
semfn_3_0 ns@(happy_var_1:(_,_,HappyTok ((TokenVar happy_var_2))):happy_var_3:(_,_,HappyTok ((TokenURI happy_var_4))):happy_rest) =  Branch (Sem_3 (CPrefix happy_var_2 happy_var_4)) ns
semfn_4_0 ns@((_,_,HappyTok ((TokenVar happy_var_1))):happy_var_2:(_,_,HappyTok ((TokenVar happy_var_3))):happy_rest) =  Branch (Sem_4 (CAUIR happy_var_1 happy_var_3)) ns
semfn_4_1 ns@(happy_var_1:happy_var_2:happy_var_3:happy_rest) =  Branch (Sem_4 (CPredicateP happy_var_1 happy_var_3)) ns
semfn_4_2 ns@(happy_var_1:happy_var_2:happy_var_3:happy_rest) =  Branch (Sem_4 (CObjectP happy_var_1 happy_var_3)) ns


type Decode_Result a = a
happy_ap = ($)
happy_return = id
instance LabelDecode (()) where 
  unpack (Sem_0 s) = s
  unpack (Sem_1 s) = s
  unpack (Sem_2 s) = s
  unpack (Sem_3 s) = s
  unpack (Sem_4 s) = s


type UserDefTok = Token
instance TreeDecode (Token) where
  decode_b f (Branch (SemTok t) []) = [happy_return t]
instance LabelDecode (Token) where
  unpack (SemTok t) = t


action 0# ( HappyTok (TokenBase) ) = Shift 3 []
action 0# ( HappyTok (TokenPrefix) ) = Shift 4 []
action 0# ( HappyTok (TokenURI _) ) = Shift 7 []
action 0# ( HappyTok (TokenVar _) ) = Shift 8 []
action 1# ( HappyTok (TokenBase) ) = Shift 3 []
action 1# ( HappyTok (TokenPrefix) ) = Shift 4 []
action 2# ( HappyTok (TokenDot) ) = Shift 15 []
action 3# ( HappyTok (TokenURI _) ) = Shift 14 []
action 4# ( HappyTok (TokenVar _) ) = Shift 13 []
action 5# ( HappyTok (TokenBase) ) = Shift 3 []
action 5# ( HappyTok (TokenPrefix) ) = Shift 4 []
action 5# ( HappyTok (TokenURI _) ) = Shift 7 []
action 5# ( HappyTok (TokenVar _) ) = Shift 8 []
action 5# ( HappyEOF ) = Accept
action 6# ( HappyTok (TokenURI _) ) = Shift 7 []
action 6# ( HappyTok (TokenVar _) ) = Shift 8 []
action 7# ( HappyTok (TokenDot) ) = Reduce [red_6]
action 7# ( HappyTok (TokenSemiColon) ) = Reduce [red_6]
action 7# ( HappyTok (TokenComma) ) = Reduce [red_6]
action 7# ( HappyTok (TokenURI _) ) = Reduce [red_6]
action 7# ( HappyTok (TokenString _) ) = Reduce [red_6]
action 7# ( HappyTok (TokenInteger _) ) = Reduce [red_6]
action 7# ( HappyTok (TokenVar _) ) = Reduce [red_6]
action 8# ( HappyTok (TokenColon) ) = Shift 9 []
action 9# ( HappyTok (TokenVar _) ) = Shift 23 []
action 10# ( HappyTok (TokenURI _) ) = Shift 7 []
action 10# ( HappyTok (TokenString _) ) = Shift 21 []
action 10# ( HappyTok (TokenInteger _) ) = Shift 22 []
action 10# ( HappyTok (TokenVar _) ) = Shift 8 []
action 11# ( HappyTok (TokenDot) ) = Shift 17 []
action 11# ( HappyTok (TokenSemiColon) ) = Shift 18 []
action 12# ( HappyTok (TokenBase) ) = Shift 3 [red_3]
action 12# ( HappyTok (TokenPrefix) ) = Shift 4 [red_3]
action 12# ( HappyTok (TokenURI _) ) = Shift 7 [red_3]
action 12# ( HappyTok (TokenVar _) ) = Shift 8 [red_3]
action 12# ( HappyEOF ) = Reduce [red_3]
action 13# ( HappyTok (TokenColon) ) = Shift 16 []
action 14# ( HappyTok (TokenDot) ) = Reduce [red_4]
action 15# ( HappyTok (TokenBase) ) = Reduce [red_1]
action 15# ( HappyTok (TokenPrefix) ) = Reduce [red_1]
action 15# ( HappyTok (TokenURI _) ) = Reduce [red_1]
action 15# ( HappyTok (TokenVar _) ) = Reduce [red_1]
action 15# ( HappyEOF ) = Reduce [red_1]
action 16# ( HappyTok (TokenURI _) ) = Shift 26 []
action 17# ( HappyTok (TokenBase) ) = Reduce [red_2]
action 17# ( HappyTok (TokenPrefix) ) = Reduce [red_2]
action 17# ( HappyTok (TokenURI _) ) = Reduce [red_2]
action 17# ( HappyTok (TokenVar _) ) = Reduce [red_2]
action 17# ( HappyEOF ) = Reduce [red_2]
action 18# ( HappyTok (TokenURI _) ) = Shift 7 []
action 18# ( HappyTok (TokenVar _) ) = Shift 8 []
action 19# ( HappyTok (TokenDot) ) = Reduce [red_11]
action 19# ( HappyTok (TokenSemiColon) ) = Reduce [red_11]
action 19# ( HappyTok (TokenComma) ) = Reduce [red_11]
action 20# ( HappyTok (TokenDot) ) = Reduce [red_8]
action 20# ( HappyTok (TokenSemiColon) ) = Reduce [red_8]
action 20# ( HappyTok (TokenComma) ) = Shift 24 []
action 21# ( HappyTok (TokenDot) ) = Reduce [red_12]
action 21# ( HappyTok (TokenSemiColon) ) = Reduce [red_12]
action 21# ( HappyTok (TokenComma) ) = Reduce [red_12]
action 22# ( HappyTok (TokenDot) ) = Reduce [red_13]
action 22# ( HappyTok (TokenSemiColon) ) = Reduce [red_13]
action 22# ( HappyTok (TokenComma) ) = Reduce [red_13]
action 23# ( HappyTok (TokenDot) ) = Reduce [red_7]
action 23# ( HappyTok (TokenSemiColon) ) = Reduce [red_7]
action 23# ( HappyTok (TokenComma) ) = Reduce [red_7]
action 23# ( HappyTok (TokenURI _) ) = Reduce [red_7]
action 23# ( HappyTok (TokenString _) ) = Reduce [red_7]
action 23# ( HappyTok (TokenInteger _) ) = Reduce [red_7]
action 23# ( HappyTok (TokenVar _) ) = Reduce [red_7]
action 24# ( HappyTok (TokenURI _) ) = Shift 7 []
action 24# ( HappyTok (TokenString _) ) = Shift 21 []
action 24# ( HappyTok (TokenInteger _) ) = Shift 22 []
action 24# ( HappyTok (TokenVar _) ) = Shift 8 []
action 25# ( HappyTok (TokenDot) ) = Reduce [red_9]
action 25# ( HappyTok (TokenSemiColon) ) = Reduce [red_9]
action 26# ( HappyTok (TokenDot) ) = Reduce [red_5]
action 27# ( HappyTok (TokenDot) ) = Reduce [red_10]
action 27# ( HappyTok (TokenSemiColon) ) = Reduce [red_10]
action 27# ( HappyTok (TokenComma) ) = Reduce [red_10]
action _ _ = Error
red_MkName {getName = 1} = (G_TurtleDoc,2 :: Int,semfn_0_0)
red_MkName {getName = 2} = (G_TurtleDoc,3 :: Int,semfn_1_0)
red_MkName {getName = 3} = (G_TurtleDoc,2 :: Int,semfn_1_1)
red_MkName {getName = 4} = (G_Directive,2 :: Int,semfn_2_0)
red_MkName {getName = 5} = (G_Directive,4 :: Int,semfn_3_0)
red_MkName {getName = 6} = (G_AbbrURI,1 :: Int,semfn_0_1)
red_MkName {getName = 7} = (G_AbbrURI,3 :: Int,semfn_4_0)
red_MkName {getName = 8} = (G_Predicates,2 :: Int,semfn_1_2)
red_MkName {getName = 9} = (G_Predicates,3 :: Int,semfn_4_1)
red_MkName {getName = 10} = (G_Object,3 :: Int,semfn_4_2)
red_MkName {getName = 11} = (G_Object,1 :: Int,semfn_0_2)
red_MkName {getName = 12} = (G_Object,1 :: Int,semfn_0_3)
red_MkName {getName = 13} = (G_Object,1 :: Int,semfn_0_4)
goto 0# G_TurtleDoc = 5#
goto 0# G_Directive = 2#
goto 0# G_AbbrURI = 6#

goto 1# G_Directive = 2#

goto 5# G_TurtleDoc = 12#
goto 5# G_Directive = 2#
goto 5# G_AbbrURI = 6#

goto 6# G_AbbrURI = 10#
goto 6# G_Predicates = 11#

goto 10# G_AbbrURI = 19#
goto 10# G_Object = 20#

goto 12# G_TurtleDoc = 12#
goto 12# G_Directive = 2#
goto 12# G_AbbrURI = 6#

goto 18# G_AbbrURI = 10#
goto 18# G_Predicates = 25#

goto 24# G_AbbrURI = 19#
goto 24# G_Object = 27#

goto _ _ = -1#
